// ─── Mock Data for Development ───
// Use this when Supabase is not connected yet.
// All data mirrors the PRD personas and examples.

import type {
    DashboardData,
    Client,
    Program,
    Enrollment,
    CheckIn,
    AISummary,
    Payment,
} from "@/types/database";

export const MOCK_COACH = {
    id: "a3f8b2c1-d4e5-6789-abcd-ef0123456789",
    email: "priya@example.com",
    full_name: "Priya Sharma",
    whatsapp_number: "+919876543210",
    country_code: "IN",
    timezone: "Asia/Kolkata",
    coaching_type: ["fitness", "wellness"],
    gateway_customer_id: null,
    gateway_account_id: null,
    plan: "basic" as const,
    checkin_day: 0,
    checkin_time: "19:00",
    slug: "priya-sharma",
    status: "active" as const,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-02-20T00:00:00Z",
};

export const MOCK_PROGRAMS: Program[] = [
    {
        id: "prog-001",
        coach_id: MOCK_COACH.id,
        name: "8-Week Fitness Kickstart",
        description: "Perfect for beginners. Build a solid foundation in 8 weeks.",
        duration_weeks: 8,
        price: 9999,
        currency: "INR",
        checkin_type: "fitness",
        is_active: true,
        created_at: "2026-01-15T00:00:00Z",
    },
    {
        id: "prog-002",
        coach_id: MOCK_COACH.id,
        name: "12-Week Transformation",
        description:
            "Full body transformation for serious results. Includes nutrition guidance.",
        duration_weeks: 12,
        price: 15000,
        currency: "INR",
        checkin_type: "fitness",
        is_active: true,
        created_at: "2026-01-15T00:00:00Z",
    },
    {
        id: "prog-003",
        coach_id: MOCK_COACH.id,
        name: "4-Week Wellness Reset",
        description: "Mindfulness, movement, and recovery focused program.",
        duration_weeks: 4,
        price: 5999,
        currency: "INR",
        checkin_type: "wellness",
        is_active: false,
        created_at: "2026-01-20T00:00:00Z",
    },
];

export const MOCK_CLIENTS: Client[] = [
    {
        id: "client-001",
        coach_id: MOCK_COACH.id,
        full_name: "Rohan Sharma",
        whatsapp_number: "+919812345001",
        email: "rohan@example.com",
        age: 28,
        primary_goal: "Weight Loss",
        health_notes: "Mild lower back pain",
        gateway_customer_id: null,
        status: "active",
        created_at: "2026-01-20T00:00:00Z",
    },
    {
        id: "client-002",
        coach_id: MOCK_COACH.id,
        full_name: "Ankita Mehta",
        whatsapp_number: "+919812345002",
        email: "ankita@example.com",
        age: 32,
        primary_goal: "Overall Fitness",
        health_notes: null,
        gateway_customer_id: null,
        status: "active",
        created_at: "2026-01-22T00:00:00Z",
    },
    {
        id: "client-003",
        coach_id: MOCK_COACH.id,
        full_name: "Neha Singh",
        whatsapp_number: "+919812345003",
        email: "neha@example.com",
        age: 25,
        primary_goal: "Muscle Gain",
        health_notes: null,
        gateway_customer_id: null,
        status: "active",
        created_at: "2026-02-01T00:00:00Z",
    },
    {
        id: "client-004",
        coach_id: MOCK_COACH.id,
        full_name: "Vikram Patel",
        whatsapp_number: "+919812345004",
        email: "vikram@example.com",
        age: 35,
        primary_goal: "Weight Loss",
        health_notes: "Type 2 diabetes — cleared by physician",
        gateway_customer_id: null,
        status: "active",
        created_at: "2026-02-03T00:00:00Z",
    },
    {
        id: "client-005",
        coach_id: MOCK_COACH.id,
        full_name: "Kavya Nair",
        whatsapp_number: "+919812345005",
        email: "kavya@example.com",
        age: 29,
        primary_goal: "Flexibility",
        health_notes: null,
        gateway_customer_id: null,
        status: "active",
        created_at: "2026-02-05T00:00:00Z",
    },
    {
        id: "client-006",
        coach_id: MOCK_COACH.id,
        full_name: "Arjun Reddy",
        whatsapp_number: "+919812345006",
        email: "arjun@example.com",
        age: 31,
        primary_goal: "Muscle Gain",
        health_notes: null,
        gateway_customer_id: null,
        status: "active",
        created_at: "2026-02-07T00:00:00Z",
    },
    {
        id: "client-007",
        coach_id: MOCK_COACH.id,
        full_name: "Meera Kulkarni",
        whatsapp_number: "+919812345007",
        email: "meera@example.com",
        age: 40,
        primary_goal: "Mental Wellness",
        health_notes: "Recovering from knee surgery",
        gateway_customer_id: null,
        status: "inactive",
        created_at: "2026-01-18T00:00:00Z",
    },
];

export const MOCK_ENROLLMENTS: Enrollment[] = [
    {
        id: "enr-001",
        coach_id: MOCK_COACH.id,
        client_id: "client-001",
        program_id: "prog-002",
        start_date: "2026-01-20",
        end_date: "2026-04-13",
        amount_paid: 15000,
        currency: "INR",
        gateway_payment_id: "pi_mock_001",
        payment_gateway: "razorpay",
        status: "active",
        renewal_reminder_1_sent: false,
        renewal_reminder_2_sent: false,
        churn_reason: null,
        created_at: "2026-01-20T00:00:00Z",
    },
    {
        id: "enr-002",
        coach_id: MOCK_COACH.id,
        client_id: "client-002",
        program_id: "prog-001",
        start_date: "2026-01-22",
        end_date: "2026-03-19",
        amount_paid: 9999,
        currency: "INR",
        gateway_payment_id: "pi_mock_002",
        payment_gateway: "razorpay",
        status: "active",
        renewal_reminder_1_sent: false,
        renewal_reminder_2_sent: false,
        churn_reason: null,
        created_at: "2026-01-22T00:00:00Z",
    },
    {
        id: "enr-003",
        coach_id: MOCK_COACH.id,
        client_id: "client-003",
        program_id: "prog-001",
        start_date: "2026-02-01",
        end_date: "2026-03-01",
        amount_paid: 9999,
        currency: "INR",
        gateway_payment_id: "pi_mock_003",
        payment_gateway: "razorpay",
        status: "active",
        renewal_reminder_1_sent: true,
        renewal_reminder_2_sent: false,
        churn_reason: null,
        created_at: "2026-02-01T00:00:00Z",
    },
];

export const MOCK_CHECKINS: CheckIn[] = [
    {
        id: "chk-001",
        coach_id: MOCK_COACH.id,
        client_id: "client-001",
        enrollment_id: "enr-001",
        week_number: 5,
        check_date: "2026-02-23",
        raw_reply: "73.2 kg, 3 sessions, energy 4, feeling tired this week",
        weight_kg: 73.2,
        sessions_completed: 3,
        energy_score: 4,
        notes: "Feeling tired this week, work stress",
        responded_at: "2026-02-23T19:30:00Z",
        message_sent_at: "2026-02-23T19:00:00Z",
        created_at: "2026-02-23T19:00:00Z",
    },
    {
        id: "chk-002",
        coach_id: MOCK_COACH.id,
        client_id: "client-002",
        enrollment_id: "enr-002",
        week_number: 5,
        check_date: "2026-02-23",
        raw_reply: "58 kg, 4 sessions, energy 3, struggling with motivation",
        weight_kg: 58,
        sessions_completed: 4,
        energy_score: 3,
        notes: "Struggling with motivation this week",
        responded_at: "2026-02-23T20:15:00Z",
        message_sent_at: "2026-02-23T19:00:00Z",
        created_at: "2026-02-23T19:00:00Z",
    },
    {
        id: "chk-003",
        coach_id: MOCK_COACH.id,
        client_id: "client-003",
        enrollment_id: "enr-003",
        week_number: 4,
        check_date: "2026-02-23",
        raw_reply: "62 kg, 5 sessions, energy 8, hit a new PR on deadlift",
        weight_kg: 62,
        sessions_completed: 5,
        energy_score: 8,
        notes: "Hit a new PR on deadlift! Feeling great",
        responded_at: "2026-02-23T19:10:00Z",
        message_sent_at: "2026-02-23T19:00:00Z",
        created_at: "2026-02-23T19:00:00Z",
    },
    {
        id: "chk-004",
        coach_id: MOCK_COACH.id,
        client_id: "client-004",
        enrollment_id: null,
        week_number: 3,
        check_date: "2026-02-23",
        raw_reply: "82.5 kg, 3 sessions, energy 7, diet going well",
        weight_kg: 82.5,
        sessions_completed: 3,
        energy_score: 7,
        notes: "Diet going well, blood sugar stable",
        responded_at: "2026-02-23T21:00:00Z",
        message_sent_at: "2026-02-23T19:00:00Z",
        created_at: "2026-02-23T19:00:00Z",
    },
    {
        id: "chk-005",
        coach_id: MOCK_COACH.id,
        client_id: "client-005",
        enrollment_id: null,
        week_number: 3,
        check_date: "2026-02-23",
        raw_reply: null,
        weight_kg: null,
        sessions_completed: null,
        energy_score: null,
        notes: null,
        responded_at: null,
        message_sent_at: "2026-02-23T19:00:00Z",
        created_at: "2026-02-23T19:00:00Z",
    },
    {
        id: "chk-006",
        coach_id: MOCK_COACH.id,
        client_id: "client-006",
        enrollment_id: null,
        week_number: 2,
        check_date: "2026-02-23",
        raw_reply: null,
        weight_kg: null,
        sessions_completed: null,
        energy_score: null,
        notes: null,
        responded_at: null,
        message_sent_at: "2026-02-23T19:00:00Z",
        created_at: "2026-02-23T19:00:00Z",
    },
];

export const MOCK_PAYMENTS: Payment[] = [
    {
        id: "pay-001",
        coach_id: MOCK_COACH.id,
        client_id: "client-001",
        enrollment_id: "enr-001",
        amount: 15000,
        currency: "INR",
        payment_type: "new",
        gateway_payment_id: "pi_mock_001",
        gateway_order_id: "order_mock_001",
        payment_gateway: "razorpay",
        gateway_payment_status: "succeeded",
        paid_at: "2026-01-20T10:00:00Z",
        created_at: "2026-01-20T10:00:00Z",
        client: MOCK_CLIENTS[0],
        program_name: "12-Week Transformation",
    },
    {
        id: "pay-002",
        coach_id: MOCK_COACH.id,
        client_id: "client-002",
        enrollment_id: "enr-002",
        amount: 9999,
        currency: "INR",
        payment_type: "new",
        gateway_payment_id: "pi_mock_002",
        gateway_order_id: "order_mock_002",
        payment_gateway: "razorpay",
        gateway_payment_status: "succeeded",
        paid_at: "2026-01-22T14:00:00Z",
        created_at: "2026-01-22T14:00:00Z",
        client: MOCK_CLIENTS[1],
        program_name: "8-Week Fitness Kickstart",
    },
    {
        id: "pay-003",
        coach_id: MOCK_COACH.id,
        client_id: "client-003",
        enrollment_id: "enr-003",
        amount: 9999,
        currency: "INR",
        payment_type: "new",
        gateway_payment_id: "pi_mock_003",
        gateway_order_id: "order_mock_003",
        payment_gateway: "razorpay",
        gateway_payment_status: "succeeded",
        paid_at: "2026-02-01T09:00:00Z",
        created_at: "2026-02-01T09:00:00Z",
        client: MOCK_CLIENTS[2],
        program_name: "8-Week Fitness Kickstart",
    },
    {
        id: "pay-004",
        coach_id: MOCK_COACH.id,
        client_id: "client-004",
        enrollment_id: null,
        amount: 15000,
        currency: "INR",
        payment_type: "new",
        gateway_payment_id: "pi_mock_004",
        gateway_order_id: "order_mock_004",
        payment_gateway: "razorpay",
        gateway_payment_status: "succeeded",
        paid_at: "2026-02-03T11:00:00Z",
        created_at: "2026-02-03T11:00:00Z",
        client: MOCK_CLIENTS[3],
        program_name: "12-Week Transformation",
    },
    {
        id: "pay-005",
        coach_id: MOCK_COACH.id,
        client_id: "client-005",
        enrollment_id: null,
        amount: 9999,
        currency: "INR",
        payment_type: "new",
        gateway_payment_id: "pi_mock_005",
        gateway_order_id: "order_mock_005",
        payment_gateway: "razorpay",
        gateway_payment_status: "succeeded",
        paid_at: "2026-02-05T16:00:00Z",
        created_at: "2026-02-05T16:00:00Z",
        client: MOCK_CLIENTS[4],
        program_name: "8-Week Fitness Kickstart",
    },
    {
        id: "pay-006",
        coach_id: MOCK_COACH.id,
        client_id: "client-001",
        enrollment_id: "enr-001",
        amount: 15000,
        currency: "INR",
        payment_type: "renewal",
        gateway_payment_id: "pi_mock_006",
        gateway_order_id: "order_mock_006",
        payment_gateway: "razorpay",
        gateway_payment_status: "succeeded",
        paid_at: "2026-02-18T12:00:00Z",
        created_at: "2026-02-18T12:00:00Z",
        client: MOCK_CLIENTS[0],
        program_name: "12-Week Transformation",
    },
];

export const MOCK_AI_SUMMARY: AISummary = {
    id: "sum-001",
    coach_id: MOCK_COACH.id,
    week_start_date: "2026-02-17",
    week_end_date: "2026-02-23",
    summary_text: `RESPONSE RATE
4 of 6 clients responded.

NEEDS ATTENTION
• Ankita M. — Energy 3/10, struggling with motivation. Schedule a personal check-in call.
• Rohan S. — Energy 4/10, work stress affecting consistency. Suggest lighter session plan this week.

STRONG PROGRESS
• Neha S. — Hit a new deadlift PR. Energy at 8/10, excellent consistency with 5 sessions.
• Vikram P. — Blood sugar stable, diet adherence strong at 3 sessions.

GROUP AVERAGE
Energy score: 5.5
Sessions per week: 3.8

THIS WEEK PRIORITY
Reach out to Ankita personally — two consecutive low-energy weeks signal risk of dropout.

NON-RESPONDERS
Kavya Nair, Arjun Reddy`,
    total_clients: 6,
    responded_count: 4,
    avg_energy_score: 5.5,
    generated_at: "2026-02-24T07:00:00Z",
    delivered_to_coach: true,
};

export const MOCK_RESPONSE_RATE_HISTORY = [
    { week: "Jan 13", rate: 75 },
    { week: "Jan 20", rate: 80 },
    { week: "Jan 27", rate: 70 },
    { week: "Feb 3", rate: 85 },
    { week: "Feb 10", rate: 90 },
    { week: "Feb 17", rate: 82 },
    { week: "Feb 24", rate: 67 },
    { week: "Mar 2", rate: 78 },
];

export const MOCK_REVENUE_HISTORY = [
    { month: "Oct", amount: 45000 },
    { month: "Nov", amount: 54998 },
    { month: "Dec", amount: 59997 },
    { month: "Jan", amount: 74997 },
    { month: "Feb", amount: 87497 },
];

export const MOCK_DASHBOARD: DashboardData = {
    active_clients: 6,
    revenue_this_month: 87497,
    currency: "INR",
    renewals_due_this_week: 1,
    checkin_response_rate_last_week: 0.67,
    clients_needing_attention: [
        {
            id: "client-001",
            name: "Rohan Sharma",
            reason: "Energy 4/10 — work stress affecting sessions",
            last_energy_score: 4,
        },
        {
            id: "client-002",
            name: "Ankita Mehta",
            reason: "Energy 3/10 — struggling with motivation",
            last_energy_score: 3,
        },
    ],
    last_summary_preview:
        "4 of 6 responded. Avg energy: 5.5. 2 clients need attention. Neha hit a new PR.",
    renewals: [
        {
            client_name: "Neha Singh",
            client_id: "client-003",
            program: "8-Week Fitness Kickstart",
            end_date: "2026-03-01",
            days_remaining: 5,
        },
    ],
};
